"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = [ 'juma_bin.py' ]
APP_NAME = 'JumaEditor'
AUTHOR = 'CloudTeam Pro'
DATA_FILES = []
OPTIONS = {
	# 'arch': 'x86_64',
	'argv_emulation': True,
	# 'optimize': 2,
	# 'strip': False,
	# 'semi_standalone' : True,
	# 'use_pythonpath'  : True,
	# 'emulate_shell_environment' : True,
	'includes':[
		'PySide.QtCore',
		'PySide.QtGui',
		],
}

setup(
    name=APP_NAME,
	author=AUTHOR,
	app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

"""
plist=dict(CFBundleName= APP_NAME,
        CFBundleDisplayName= APP_NAME,
        CFBundleVersion= "0.1.0",
        CFBundleShortVersionString= "0.1.0",)
"""