-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:0470e6fee9c503a828741caf9ba71ea3:0cf1171cc69766107c8f52ddebf1070a:b75d113e72cf93e9cbb321019551037e$
-- 

return {
	texture = 'editor_asset.png',
	frames = {
			{
				name = "barHorizontal_blue_left.png",
				spriteColorRect = { x = 0, y = 0, width = 6, height = 26 },
				uvRect = { u0 = 0.519504, v0 = 0.00177305, u1 = 0.530142, v1 = 0.0478723 },
				spriteSourceSize = { width = 6, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barHorizontal_blue_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 16, height = 26 },
				uvRect = { u0 = 0.214539, v0 = 0.820922, u1 = 0.242908, v1 = 0.867021 },
				spriteSourceSize = { width = 16, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barHorizontal_blue_right.png",
				spriteColorRect = { x = 0, y = 0, width = 6, height = 26 },
				uvRect = { u0 = 0.519504, v0 = 0.0514184, u1 = 0.530142, v1 = 0.0975177 },
				spriteSourceSize = { width = 6, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barHorizontal_green_left.png",
				spriteColorRect = { x = 0, y = 0, width = 6, height = 26 },
				uvRect = { u0 = 0.519504, v0 = 0.101064, u1 = 0.530142, v1 = 0.147163 },
				spriteSourceSize = { width = 6, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barHorizontal_green_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 16, height = 26 },
				uvRect = { u0 = 0.214539, v0 = 0.870567, u1 = 0.242908, v1 = 0.916667 },
				spriteSourceSize = { width = 16, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barHorizontal_green_right.png",
				spriteColorRect = { x = 0, y = 0, width = 6, height = 26 },
				uvRect = { u0 = 0.519504, v0 = 0.150709, u1 = 0.530142, v1 = 0.196809 },
				spriteSourceSize = { width = 6, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barHorizontal_red_left.png",
				spriteColorRect = { x = 0, y = 0, width = 6, height = 26 },
				uvRect = { u0 = 0.973404, v0 = 0.00177305, u1 = 0.984043, v1 = 0.0478723 },
				spriteSourceSize = { width = 6, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barHorizontal_red_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 16, height = 26 },
				uvRect = { u0 = 0.214539, v0 = 0.920213, u1 = 0.242908, v1 = 0.966312 },
				spriteSourceSize = { width = 16, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barHorizontal_red_right.png",
				spriteColorRect = { x = 0, y = 0, width = 6, height = 26 },
				uvRect = { u0 = 0.987589, v0 = 0.00177305, u1 = 0.998227, v1 = 0.0478723 },
				spriteSourceSize = { width = 6, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barHorizontal_shadow_left.png",
				spriteColorRect = { x = 0, y = 0, width = 6, height = 26 },
				uvRect = { u0 = 0.973404, v0 = 0.0514184, u1 = 0.984043, v1 = 0.0975177 },
				spriteSourceSize = { width = 6, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barHorizontal_shadow_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 16, height = 26 },
				uvRect = { u0 = 0.934397, v0 = 0.182624, u1 = 0.962766, v1 = 0.228723 },
				spriteSourceSize = { width = 16, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barHorizontal_shadow_right.png",
				spriteColorRect = { x = 0, y = 0, width = 6, height = 26 },
				uvRect = { u0 = 0.987589, v0 = 0.0514184, u1 = 0.998227, v1 = 0.0975177 },
				spriteSourceSize = { width = 6, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barHorizontal_white_left.png",
				spriteColorRect = { x = 0, y = 0, width = 6, height = 26 },
				uvRect = { u0 = 0.973404, v0 = 0.101064, u1 = 0.984043, v1 = 0.147163 },
				spriteSourceSize = { width = 6, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barHorizontal_white_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 16, height = 26 },
				uvRect = { u0 = 0.966312, v0 = 0.200355, u1 = 0.994681, v1 = 0.246454 },
				spriteSourceSize = { width = 16, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barHorizontal_white_right.png",
				spriteColorRect = { x = 0, y = 0, width = 6, height = 26 },
				uvRect = { u0 = 0.987589, v0 = 0.101064, u1 = 0.998227, v1 = 0.147163 },
				spriteSourceSize = { width = 6, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barHorizontal_yellow_left.png",
				spriteColorRect = { x = 0, y = 0, width = 6, height = 26 },
				uvRect = { u0 = 0.973404, v0 = 0.150709, u1 = 0.984043, v1 = 0.196809 },
				spriteSourceSize = { width = 6, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barHorizontal_yellow_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 16, height = 26 },
				uvRect = { u0 = 0.934397, v0 = 0.23227, u1 = 0.962766, v1 = 0.278369 },
				spriteSourceSize = { width = 16, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barHorizontal_yellow_right.png",
				spriteColorRect = { x = 0, y = 0, width = 6, height = 26 },
				uvRect = { u0 = 0.987589, v0 = 0.150709, u1 = 0.998227, v1 = 0.196809 },
				spriteSourceSize = { width = 6, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barVertical_blue_bottom.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 6 },
				uvRect = { u0 = 0.00177305, v0 = 0.987589, u1 = 0.0478723, v1 = 0.998227 },
				spriteSourceSize = { width = 26, height = 6 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barVertical_blue_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 16 },
				uvRect = { u0 = 0.554965, v0 = 0.420213, u1 = 0.601064, v1 = 0.448582 },
				spriteSourceSize = { width = 26, height = 16 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barVertical_blue_top.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 6 },
				uvRect = { u0 = 0.0514184, v0 = 0.987589, u1 = 0.0975177, v1 = 0.998227 },
				spriteSourceSize = { width = 26, height = 6 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barVertical_green_bottom.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 6 },
				uvRect = { u0 = 0.101064, v0 = 0.987589, u1 = 0.147163, v1 = 0.998227 },
				spriteSourceSize = { width = 26, height = 6 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barVertical_green_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 16 },
				uvRect = { u0 = 0.554965, v0 = 0.452128, u1 = 0.601064, v1 = 0.480496 },
				spriteSourceSize = { width = 26, height = 16 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barVertical_green_top.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 6 },
				uvRect = { u0 = 0.150709, v0 = 0.97695, u1 = 0.196809, v1 = 0.987589 },
				spriteSourceSize = { width = 26, height = 6 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barVertical_red_bottom.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 6 },
				uvRect = { u0 = 0.200355, v0 = 0.97695, u1 = 0.246454, v1 = 0.987589 },
				spriteSourceSize = { width = 26, height = 6 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barVertical_red_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 16 },
				uvRect = { u0 = 0.884752, v0 = 0.182624, u1 = 0.930851, v1 = 0.210993 },
				spriteSourceSize = { width = 26, height = 16 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barVertical_red_top.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 6 },
				uvRect = { u0 = 0.60461, v0 = 0.182624, u1 = 0.650709, v1 = 0.193262 },
				spriteSourceSize = { width = 26, height = 6 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barVertical_shadow_bottom.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 6 },
				uvRect = { u0 = 0.654255, v0 = 0.182624, u1 = 0.700355, v1 = 0.193262 },
				spriteSourceSize = { width = 26, height = 6 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barVertical_shadow_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 16 },
				uvRect = { u0 = 0.884752, v0 = 0.214539, u1 = 0.930851, v1 = 0.242908 },
				spriteSourceSize = { width = 26, height = 16 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barVertical_shadow_top.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 6 },
				uvRect = { u0 = 0.640071, v0 = 0.239362, u1 = 0.650709, v1 = 0.285461 },
				spriteSourceSize = { width = 26, height = 6 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "barVertical_white_bottom.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 6 },
				uvRect = { u0 = 0.640071, v0 = 0.289007, u1 = 0.650709, v1 = 0.335106 },
				spriteSourceSize = { width = 26, height = 6 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "barVertical_white_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 16 },
				uvRect = { u0 = 0.884752, v0 = 0.246454, u1 = 0.930851, v1 = 0.274823 },
				spriteSourceSize = { width = 26, height = 16 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barVertical_white_top.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 6 },
				uvRect = { u0 = 0.640071, v0 = 0.338652, u1 = 0.650709, v1 = 0.384752 },
				spriteSourceSize = { width = 26, height = 6 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "barVertical_yellow_bottom.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 6 },
				uvRect = { u0 = 0.640071, v0 = 0.388298, u1 = 0.650709, v1 = 0.434397 },
				spriteSourceSize = { width = 26, height = 6 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "barVertical_yellow_mid.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 16 },
				uvRect = { u0 = 0.884752, v0 = 0.278369, u1 = 0.930851, v1 = 0.306738 },
				spriteSourceSize = { width = 26, height = 16 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "barVertical_yellow_top.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 6 },
				uvRect = { u0 = 0.611702, v0 = 0.420213, u1 = 0.62234, v1 = 0.466312 },
				spriteSourceSize = { width = 26, height = 6 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "crossair_black.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.544326, v0 = 0.136525, u1 = 0.601064, v1 = 0.193262 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "crossair_blackOutline.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 36 },
				uvRect = { u0 = 0.147163, v0 = 0.842199, u1 = 0.210993, v1 = 0.906028 },
				spriteSourceSize = { width = 36, height = 36 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "crossair_blue.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.45922, v0 = 0.00177305, u1 = 0.515957, v1 = 0.0585106 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "crossair_blueOutline.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 36 },
				uvRect = { u0 = 0.147163, v0 = 0.909574, u1 = 0.210993, v1 = 0.973404 },
				spriteSourceSize = { width = 36, height = 36 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "crossair_red.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.45922, v0 = 0.0620567, u1 = 0.515957, v1 = 0.118794 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "crossair_redOutline.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 36 },
				uvRect = { u0 = 0.544326, v0 = 0.00177305, u1 = 0.608156, v1 = 0.0656028 },
				spriteSourceSize = { width = 36, height = 36 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "crossair_white.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.45922, v0 = 0.12234, u1 = 0.515957, v1 = 0.179078 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "crossair_whiteOutline.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 36 },
				uvRect = { u0 = 0.544326, v0 = 0.0691489, u1 = 0.608156, v1 = 0.132979 },
				spriteSourceSize = { width = 36, height = 36 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cursor_hand.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 30 },
				uvRect = { u0 = 0.45922, v0 = 0.182624, u1 = 0.512411, v1 = 0.235816 },
				spriteSourceSize = { width = 30, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cursor_pointer3D.png",
				spriteColorRect = { x = 0, y = 0, width = 20, height = 24 },
				uvRect = { u0 = 0.618794, v0 = 0.200355, u1 = 0.661348, v1 = 0.235816 },
				spriteSourceSize = { width = 20, height = 24 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "cursor_pointer3D_shadow.png",
				spriteColorRect = { x = 0, y = 0, width = 20, height = 27 },
				uvRect = { u0 = 0.515957, v0 = 0.200355, u1 = 0.56383, v1 = 0.235816 },
				spriteSourceSize = { width = 20, height = 27 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "cursor_pointerFlat.png",
				spriteColorRect = { x = 0, y = 0, width = 20, height = 24 },
				uvRect = { u0 = 0.45922, v0 = 0.420213, u1 = 0.501773, v1 = 0.455674 },
				spriteSourceSize = { width = 20, height = 24 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "cursor_pointerFlat_shadow.png",
				spriteColorRect = { x = 0, y = 0, width = 20, height = 27 },
				uvRect = { u0 = 0.567376, v0 = 0.200355, u1 = 0.615248, v1 = 0.235816 },
				spriteSourceSize = { width = 20, height = 27 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "dotBlue.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 24 },
				uvRect = { u0 = 0.934397, v0 = 0.281915, u1 = 0.97695, v1 = 0.324468 },
				spriteSourceSize = { width = 24, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dotGreen.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 24 },
				uvRect = { u0 = 0.884752, v0 = 0.310284, u1 = 0.927305, v1 = 0.352837 },
				spriteSourceSize = { width = 24, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dotRed.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 24 },
				uvRect = { u0 = 0.930851, v0 = 0.328014, u1 = 0.973404, v1 = 0.370567 },
				spriteSourceSize = { width = 24, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dotWhite.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 24 },
				uvRect = { u0 = 0.884752, v0 = 0.356383, u1 = 0.927305, v1 = 0.398936 },
				spriteSourceSize = { width = 24, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dotYellow.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 24 },
				uvRect = { u0 = 0.654255, v0 = 0.39539, u1 = 0.696809, v1 = 0.437943 },
				spriteSourceSize = { width = 24, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dot_shadow.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 24 },
				uvRect = { u0 = 0.930851, v0 = 0.374113, u1 = 0.973404, v1 = 0.416667 },
				spriteSourceSize = { width = 24, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "glassPanel.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.00177305, v0 = 0.661348, u1 = 0.179078, v1 = 0.838652 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "glassPanel_cornerBL.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.182624, v0 = 0.45922, u1 = 0.359929, v1 = 0.636525 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "glassPanel_cornerBR.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.182624, v0 = 0.640071, u1 = 0.359929, v1 = 0.817376 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "glassPanel_cornerTL.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.25, v0 = 0.820922, u1 = 0.427305, v1 = 0.998227 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "glassPanel_cornerTR.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.363475, v0 = 0.45922, u1 = 0.54078, v1 = 0.636525 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "glassPanel_corners.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.363475, v0 = 0.640071, u1 = 0.54078, v1 = 0.817376 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "glassPanel_projection.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.430851, v0 = 0.820922, u1 = 0.608156, v1 = 0.998227 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "glassPanel_tab.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 112 },
				uvRect = { u0 = 0.00177305, v0 = 0.45922, u1 = 0.179078, v1 = 0.657801 },
				spriteSourceSize = { width = 100, height = 112 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "metalPanel.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.611702, v0 = 0.00177305, u1 = 0.789007, v1 = 0.179078 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "metalPanel_blue.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.792553, v0 = 0.00177305, u1 = 0.969858, v1 = 0.179078 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "metalPanel_blueCorner.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.45922, v0 = 0.239362, u1 = 0.636525, v1 = 0.416667 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "metalPanel_green.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.703901, v0 = 0.182624, u1 = 0.881206, v1 = 0.359929 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "metalPanel_greenCorner.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.703901, v0 = 0.363475, u1 = 0.881206, v1 = 0.54078 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "metalPanel_plate.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 80 },
				uvRect = { u0 = 0.00177305, v0 = 0.842199, u1 = 0.143617, v1 = 0.984043 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "metalPanel_red.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.544326, v0 = 0.544326, u1 = 0.721631, v1 = 0.721631 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "metalPanel_redCorner.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.611702, v0 = 0.725177, u1 = 0.789007, v1 = 0.902482 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "metalPanel_yellow.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.725177, v0 = 0.544326, u1 = 0.902482, v1 = 0.721631 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "metalPanel_yellowCorner.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 100 },
				uvRect = { u0 = 0.792553, v0 = 0.725177, u1 = 0.969858, v1 = 0.902482 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "moai.png",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.00177305, v0 = 0.00177305, u1 = 0.455674, v1 = 0.455674 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "squareBlue.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 26 },
				uvRect = { u0 = 0.505319, v0 = 0.420213, u1 = 0.551418, v1 = 0.453901 },
				spriteSourceSize = { width = 19, height = 26 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "squareGreen.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 26 },
				uvRect = { u0 = 0.664894, v0 = 0.196809, u1 = 0.698582, v1 = 0.242908 },
				spriteSourceSize = { width = 19, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "squareRed.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 26 },
				uvRect = { u0 = 0.654255, v0 = 0.246454, u1 = 0.700355, v1 = 0.280142 },
				spriteSourceSize = { width = 19, height = 26 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "squareWhite.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 26 },
				uvRect = { u0 = 0.654255, v0 = 0.283688, u1 = 0.700355, v1 = 0.317376 },
				spriteSourceSize = { width = 19, height = 26 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "squareYellow.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 26 },
				uvRect = { u0 = 0.654255, v0 = 0.320922, u1 = 0.700355, v1 = 0.35461 },
				spriteSourceSize = { width = 19, height = 26 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "square_shadow.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 26 },
				uvRect = { u0 = 0.654255, v0 = 0.358156, u1 = 0.700355, v1 = 0.391844 },
				spriteSourceSize = { width = 19, height = 26 },
				spriteTrimmed = false,
				textureRotated = true
			},
		}
	}

