#!/usr/bin/env python

import logging
import os
import os.path

##----------------------------------------------------------------##
def _saveLayoutToFile( path, text ):
	output = """
----------------------------------------------------------------
--
-- generated by layout.py
--
----------------------------------------------------------------
 """
	output += "return " + text
	file = open(path, 'w')
	file.write(output)
	file.close()